### ISSUE TITLE
out of bound access?

### ISSUE THREAD

**Issue by KingDuckZ** [hostilefork/nocycle#1]
I added the following assert at Nstate.hpp:103

```
    assert(digit < m_table.size());
```

This looks like a very common condition given that digit is used to index m_table (digit = 20 in my case). However the assert fails. In my code I'm calling AddEdge() and that eventually causes my assert to fail.

Strangely there is no crash if I remove the assert, but I think this is an out of bound access error. Is this a known problem? If not can someone please look into this?

**Comment by hostilefork** [comment]
Looks like you're right, there was a fetch of the value even when it wasn't used:

https://github.com/hostilefork/nocycle/commit/14109395057367802350690678b156ca4bfb2014

I'm pretty busy right now but I can try to help if you have questions on this.  I got mid-way through a cleanup of this project, and didn't really finish doing that.  At one point I had intended to factor Nstate out into its own GitHub project and find a good way to package it...but what wound up happening is that there were two copies, and I came back to it a decade later not sure what the situation was.

Since Nocycle compiled with the Nstate version in its own directory, and that seems to be what it's using, I consolidated to that version for now:

https://github.com/hostilefork/nocycle/commit/71e48484ae6eef74ba92d72ed4f0d62bff5a7e4e

**Comment by KingDuckZ** [comment]
Thanks for the quick fix! I can confirm it's all working correctly now!

**Comment by hostilefork** [comment]
> Thanks for the quick fix! I can confirm it's all working correctly now!

Glad to help, and glad it works...this is a very old thing I wrote!

*(For those interested: It was actually a response to an online application question from what-was-once-[Freebase](https://en.wikipedia.org/wiki/Freebase).  I had moved to the SF bay area, and I'd been curious about their work...and wanted to talk to the people involved.  I tried to do so via published email addresses, but lacking success in that I tried to contact them through their job application.  This was my somewhat elaborate (and--I think--kind of humorous) answer to their "submit C code to detect a cycle in an acyclic graph) question.  :-P  It is not representative of how I'd write code now a decade later, but I don't think it's that bad.)*
